language: julia

sudo: required

services:
    - docker

os:
    - linux

julia:
    - 0.3
    - 0.4

notifications:
    email: false

after_success:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("OffsetArrays"))`); Pkg.pin("OffsetArrays"); Pkg.resolve()'
  - julia -e 'using OffsetArrays; @assert isdefined(:OffsetArrays); @assert typeof(OffsetArrays) === Module'
